#pragma once

#include <vector>
#include <map>
#include <set>

#include "MathFunctions.h"

const std::string FUNCTION_ERROR = ". Invalid number of function arguments.";
const std::string VARIABLE_ERROR = ". Illegal characters in variable name.";
const std::string CONST_ERROR = ". Illegal characters in number.";

// This class represents a single symbol in mathematical formula,
// for example '*', 'sin', 'a1', '245'. Its children are arguments
// of an function/operator. 
class Node {

public:
    // Creates FunctionNode, VariableNode or OperationNode depending
    // on the symbol and assigns id to them
    static Node *create(const std::string &symbol, int id = -1);

    Node(const std::string &symbol, int id);

    void set_child(int i, Node *child);

    int get_child_count() const;

    // Collect all child symbols and returns all symbols combined
    // in reverse notation
    std::string to_string() const;

    // Fixes node based on specification
    // Each node has its own fixing mechanism
    virtual void fix() = 0;

    // If exists, returns error string generated during 'fix'
    // else returns empty string
    std::string get_error() const;

    // returns errors and ids of all the child Nodes, including this one
    std::vector<std::pair<std::string, int> > get_errors() const;

    // Returns all variable names in this and child nodes
    std::set<std::string> get_variables() const;

    // Returns result of math formula given current variables
    virtual float evaluate(std::map<std::string, int> &values) const = 0;

    // Replaces rightmost leaf if possible
    void replace_rightmost(Node *replacement);

    // Returns rightmost leaf or null, if node has no children
    Node *get_rightmost();

    // Const version of "get_rightmost()"
    const Node *get_rightmost() const;

    ~Node();
protected:
    int child_count;
    std::string symbol;
    Node** children;
    // Error generated by the fix function
    std::string error;
    // Id of the node, needed to know which nodes generated which errors
    int id;

    void collect_errors(std::vector<std::pair<std::string, int> > &errors) const;

    virtual void collect_variables(std::set<std::string> &variables) const;

    static bool is_digit(char c);

    static bool is_letter(char c);
};




class FunctionNode :public Node {

public:
    FunctionNode(const MathFuction &f, int id);

    void fix();

    float evaluate(std::map<std::string, int> &values) const;

private:
    const MathFuction f;
};




class VariableNode :public Node {

public:
    VariableNode(const std::string &v, int id);

    void fix();

    float evaluate(std::map<std::string, int> &values) const;

protected:
    void collect_variables(std::set<std::string> &variables) const;
};




class ConstNode :public Node {

public:
    ConstNode(const std::string &c, int id);

    void fix();

    float evaluate(std::map<std::string, int> &_) const;

private:
    int to_int(std::string str);
    
    int value;
};